# Site settings
title: Leon's Blog
email: gl2001wl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's a technical blog which made by Leon Guo, 
  who is a SDE working for Oracle. 
  He focus on Java, J2EE, distributed storage/computation etc.
baseurl: "/leonblog" # the subpath of your site, e.g. /blog/
url: "http://gl2001wl.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: gl2001wl

# Build settings
markdown: kramdown

highlighter: pygments
layout: post
